wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.14
    start_time: 1664917809.063451
    t:
      1:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 12
      - 53
      - 55
      3:
      - 23
      4: 3.9.14
      5: 0.13.3
      8:
      - 1
      - 5
